import { createPagesFunctionHandler } from '@react-router/cloudflare';
import type { ServerBuild } from 'react-router';

import { getLoadContext } from '../loadContext';

// biome-ignore lint/suspicious/noTsIgnore: See below
// @ts-ignore - the server build file is generated by `react-router typegen`
import * as build from '../build/server';

export const onRequest = createPagesFunctionHandler({
    build: build as ServerBuild,
    getLoadContext,
});
