[package]
name = "yanniang-usecase"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
async-trait = "0.1.85"
chrono = "0.4.39"
color-eyre = "0.6.3"
tracing = "0.1.41"
uuid = { version = "1.13.1", features = ["v7"] }
yanniang-domain = { path = "../domain" }
